name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - develop

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: latest

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: login to registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build image
        run: |
          docker version
          docker compose version
          docker compose build
          docker compose up -d
          docker ps
      - name: test docker
        run: |
          docker exec -t slurmctld srun -N 2 hostname
