name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - develop

env:
  IMAGE_TAG: latest

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Setup Docker
        run: |
          docker version
          docker compose version
          docker compose build
          docker compose up -d
          docker ps
      - name: Test Docker
        run: |
          docker exec -t slurmctld srun -n 4 hostname
